// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rovgiojahhdothjujfzs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJvdmdpb2phaGhkb3RoanVqZnpzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjAzMDk5NTksImV4cCI6MjA3NTg4NTk1OX0.MYQB_aZLZjpKKnFDB-gkAY0oOqOin7fGBcdukmRDhBY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});